### ISSUE TITLE
Bugliste

### ISSUE THREAD

**Issue by jimbeam72** [MqAbdul/kvtanoalife#17]
- [ ] Heli Garagen & Spawn Punkte Rebellenaussenposten
- [x] Unterer Flughafen Falscher Spawnpunkt für Vehicle
- [x] Tunabaka 2x Markt
- [x] Unten Links Polizei Heli Spawn falsch
- [x] Unten Rechts kein Heli Spawn ; keine Garage; kein einparken
- [x] Polizei ATM (fast überall)
- [ ] Genral Store einfügen
- [x] Ölverabeiter Höhe anpassen
- Rebellen: 

- [x] [ ]keine Kabelbinder; 
- [ ]                  [ ]Augenbinde; 
- [ ]                  [ ]Handy abnehmen

- [ ] Polizei können Fahrzeuge nicht flippen
- [x] Debug Konsole prüfen ?!
- [x] Spielermarker können nicht enfernt werden
- [ ] Sidechat Talkpower ausstellen
- [x] Polizei Rücksäcke unsichtbar machen
- [x] Todesmarker für Polizei und Medics einfügen

**Comment by MqAbdul** [comment]
Todesmarker?

**Comment by MqAbdul** [comment]
Spielermarker inwiefern?

**Comment by MqAbdul** [comment]
Debug Konsole wtf?

**Comment by MqAbdul** [comment]
Rucksack unsichtbar müsste getestet werden

**Comment by jimbeam72** [comment]
Ich war leider nur Schriftführer dieser Liste, somit kann ich nichts zu deren Korrektheit sagen.
Fehler soll Slovakiadragon festgestellt haben.

Todesmarker: der Marker den Medics & Polizei beim Ableben eines Civ´s bekommen
Spielermarker: Den Marker, den Spieler auf der MAP setzen können
Debug Konsole: wurde bereits von mir angemerkt, dass diese bestimmt nicht übers Admin Menü OHNE richtig eingeloggt zu sein geöffnet werden kann

**Comment by MqAbdul** [comment]
Todasmarker werden nach dem requesten erstellt
spielermarker folgt
doch adminlvl5 ist die höchste stufe 
und somit können mehrer gleichezitig damit arbeiten

**Comment by Slovakiadragon** [comment]
https://native-network.net/forum/thread/7006-tanoa-krankenhaus-editor-frage/ KH Script!

**Comment by Slovakiadragon** [comment]
Kabelbinder: https://www.tukku.de/index.php/Thread/441-Tutorial-Kabelbinder-f%C3%BCr-Zivilisten-Altis-Life-Verison-4-5-5-0-0/#codeLine_1_0451fd

TESTPHASE!

**Comment by mqteggy** [comment]
Wo _Genstore einfügen_ ?

**Comment by MqAbdul** [comment]
Bugliste wird geclosed bitte einzelne issues öffnen > übersichtlichkeit
