### ISSUE TITLE
Shops anpassen

### ISSUE THREAD

**Issue by MqAbdul** [MqAbdul/kvtanoalife#18]
Könnte jemand bitte die Shops anpassen? 
Schaffe das leider grad nicht selbst, da sich der DynMarket vor seiner Implementierung flüchtet -.- 

Betroffene Dateien sind: 
Pfad: tanoa_life.tanoa\config
- [x] Config_vItems.hpp
- [x] Config_Clothing.hpp
- [x] Config_Weapons.hpp
- [x] Config_Vehicles.hpp
Kann sein das ich was vergessen habe > wenn Fragen hier oder im TS

**Comment by MqAbdul** [comment]
Bei den Preisen bitte an den vorhandenen orientieren =) Danke

**Comment by jimbeam72** [comment]
Config_Vehicles.hpp angefangen:
- Fahrzeuge eingefügt
- Skins zum Teil (CIV / REBEL / VIP / ADMIN fehlt)
