### ISSUE TITLE
Idee zu System für unsere Mapper

### ISSUE THREAD

**Issue by MqAbdul** [MqAbdul/kvtanoalife#20]
Regeln:
1. Beim Mappen im TS sein auch wenn gemuted (geht darum das ihr euch sehen könnt und absprechen)
2. In dieser Issue ein Kommentar verfassen, wenn man beginnt zu mappen und es wieder beendet
3. Vor dem Mappen diese Issue auf neue Kommentare überprüfen. 

Beispiel folgt unten drunter :P 

Diese Regeln sind nur für Bugfixes an der Map gedacht, d.h. sollte neuer Content eingefügt werden wird dies durch Mergen der Maps getan und somit steht sich keiner im Weg. Sollte allerdings an der bestehenden Map Änderungen vorgenommen werden sind die Regeln zu befolgen um Fehler zu vermeiden. Ebenfalls immer die Mission syncen in GitHub!

**Comment by MqAbdul** [comment]
Beginne zu Mappen

**Comment by MqAbdul** [comment]
Mappen beendet 05.26 Uhr

**Comment by mqteggy** [comment]
12:09 - Beginn Slots umbenennen

**Comment by mqteggy** [comment]
13:40 - Fertig

**Comment by Slovakiadragon** [comment]
Übernimmt z.Z. Leon
