### ISSUE TITLE
Kabelbinder

### ISSUE THREAD

**Issue by MqAbdul** [MqAbdul/kvtanoalife#24]
Vorerst reverted, da mehrere syntax fehler

**Comment by jimbeam72** [comment]
Anleitung, die auch bei der 5.0 passen soll:
https://www.tukku.de/index.php/Thread/441-Tutorial-Kabelbinder-f%C3%BCr-Zivilisten-Altis-Life-Verison-4-5-5-0-0/?postID=1609

**Comment by Slovakiadragon** [comment]
Habe genau das selbe Tutorial genutzt.. Mittlerweile haben die selbst Fehler  entdeckt ;-)
Ist nun verbessert
